### ISSUE TITLE
resource gateway: panic: interface conversion: runtime.Object is nil, not *unstructured.Unstructured

### ISSUE THREAD

**Issue by hideto0710** [argoproj/argo-events#183]
**Describe the bug**

I got errors below.

*resource-events*
```
starting gateway server
[2m2019-02-25T08:55:33Z[0m | info | msg: operating on event source | event-source-name:foo
[2m2019-02-25T08:55:33Z[0m | info | msg: starting to watch to resource notifications | event-source-name:foo
[2m2019-02-25T08:57:18Z[0m | warn | msg: object to watch is nil | event-source-name:foo
panic: interface conversion: runtime.Object is nil, not *unstructured.Unstructured goroutine 31 [running]: github.com/argoproj/argo-events/gateways/core/resource.(*ResourceEventSourceExecutor).listenEvents.func1(0xc420305330, 0xc4200acd20, 0xc4200a0320, 0x13604e0, 0xc420451980, 0xc420485d80, 0xc42008c3c0, 0xc4203aa1e0, 0xc4200ac780, 0xc42008c360) /Users/vpage/go/src/github.com/argoproj/argo-events/gateways/core/resource/start.go:92 +0x4f0 created by github.com/argoproj/argo-events/gateways/core/resource.(*ResourceEventSourceExecutor).listenEvents /Users/vpage/go/src/github.com/argoproj/argo-events/gateways/core/resource/start.go:79 +0x251
```
And then restarted, but not `starting to watch to resource` .

*gateway-client*
```
[2m2019-02-25T08:57:18Z[0m | error | msg: failed to receive event from stream | [31merror=[0m[31m"rpc error: code = Unavailable desc = transport is closing"[0m event-source-name:foo gateway-name:sample-resource-gateway gateway-namespace:argo-events
[2m2019-02-25T08:57:18Z[0m | info | msg: received a gateway state update notification | gateway-name:sample-resource-gateway gateway-namespace:argo-events
[2m2019-02-25T08:57:18Z[0m | info | msg: marking node phase | gateway-name:sample-resource-gateway gateway-namespace:argo-events node-id:1819460354 node-name:foo phase:Error
[2m2019-02-25T08:57:18Z[0m | info | msg: phase marked | gateway-name:sample-resource-gateway gateway-namespace:argo-events new-phase:Error node-id:1819460354 node-name:foo old-phase:Running
```

**To Reproduce**
Follow [this guide](https://github.com/argoproj/argo-events/blob/master/gateways/core/resource/install.md).

**Expected behavior**
no errors or restart correctly.

**Environment (please complete the following information):**
 - argoproj/gateway-controller:v0.7
 - argoproj/sensor-controller:v0.7
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
In my code(not example), _sometimes_ , triggers succeeded if I started sensor before starting gateway.

**Comment by VaibhavPage** [comment]
Thanks for submitting this issue. I'll create a patch to address it soon.

**Comment by VaibhavPage** [comment]
fix is released in v0.8, let me know if you still see the issue

**Comment by VaibhavPage** [comment]
One more update, v0.8.1 is released for resource gateway which let you define the type of event you are interested in. https://github.com/argoproj/argo-events/blob/a1fa700250440d56c7cdf557bbae56af7cce2392/examples/gateways/resource-gateway-configmap.yaml#L12

**Comment by VaibhavPage** [comment]
Closing this issue for now.
