### ISSUE TITLE
nil-pointer in 3rd-party library 2

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1949]
github.com/argoproj/argo-events/eventbus/jetstream/sensor.NewJetstreamTriggerConn() uses github.com/Knetic/govaluate to evaluate dependency expressions. 
[This](https://github.com/argoproj/argo-events/blob/master/eventbus/jetstream/sensor/trigger_conn.go#L69) is the line that creates an expression:

https://github.com/argoproj/argo-events/blob/master/eventbus/jetstream/sensor/trigger_conn.go 
connection.evaluableExpression, err = govaluate.NewEvaluableExpression(strings.ReplaceAll(dependencyExpression, "-", "\\-"))

A well-crafted dependencyExpression can cause Argo-Events to crash.

To reproduce:

```go
package sensor

import (
        "strings"
        "github.com/Knetic/govaluate"
)

func Reproduce() int {
      input := []byte{0x2,0x2,0x5c}
    _, _ = govaluate.NewEvaluableExpression(strings.ReplaceAll(string(input), "-", "\\-"))
```

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-b3dc9d19-7fff-35dd-9637-20334407bfa5"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Running the above code will result in the following stacktrace:</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

panic: runtime error: index out of range [3] with length 3goroutine 17 [running, locked to thread]:github.com/Knetic/govaluate.(*lexerStream).readCharacter(...)        github.com/Knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/lexerStream.go:28github.com/Knetic/govaluate.readUntilFalse(0x10c0002c6f30, 0x0, 0x1, 0x1, 0x2030d68)        github.com/Knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/parsing.go:319 +0x39egithub.com/Knetic/govaluate.readTokenUntilFalse(0x2, 0x0)        github.com/Knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/parsing.go:296 +0x39github.com/Knetic/govaluate.readToken(0x10c0002c6f30, {0x0, 0x1, 0x0, {0x2b132c0, 0xa, 0xa}}, 0x3)        github.com/Knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/parsing.go:240 +0xeafgithub.com/Knetic/govaluate.parseTokens({0x10c0002ccd68, 0x3}, 0x0)        github.com/Knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/parsing.go:28 +0x189github.com/Knetic/govaluate.NewEvaluableExpressionWithFunctions({0x10c0002ccd68, 0x3}, 0x1b83b65)        github.com/Knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:99 +0x94github.com/Knetic/govaluate.NewEvaluableExpression(...)        github.com/Knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:47
--

</div><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The issue is also present here:&nbsp;</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><a href="https://github.com/argoproj/argo-events/blob/master/common/boolminifier.go#L45" style="text-decoration:none;"><span style="font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://github.com/argoproj/argo-events/blob/master/common/boolminifier.go#L45</span></a></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><a href="https://github.com/argoproj/argo-events/blob/master/sensors/listener.go#L131" style="text-decoration:none;"><span style="font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://github.com/argoproj/argo-events/blob/master/sensors/listener.go#L131</span></a></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><a href="https://github.com/argoproj/argo-events/blob/master/eventbus/stan/sensor/trigger_conn.go#L324" style="text-decoration:none;"><span style="font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://github.com/argoproj/argo-events/blob/master/eventbus/stan/sensor/trigger_conn.go#L324</span></a></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><a href="https://github.com/argoproj/argo-events/blob/master/sensors/dependencies/filter.go#L149" style="text-decoration:none;"><span style="font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://github.com/argoproj/argo-events/blob/master/sensors/dependencies/filter.go#L149</span></a></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><br /></li></ul></b>

**Comment by whynowy** [comment]
That kind of well-crafted input won't be able to happen in real use cases.
