### ISSUE TITLE
Creating Webhook Sensor Crashes Sensor-Controller

### ISSUE THREAD

**Issue by pplavetzki** [argoproj/argo-events#231]
**Describe the bug**
When following the Installation using kubectl and Getting Started example, the Create webhook sensor step causes the sensor-controller to crash.

**To Reproduce**
1. Follow the Installation steps in the readme verbatim. 
2. Everything seems to be working correctly until the step to deploy the webhook sensor, after executing that command the:
`kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/examples/sensors/webhook-http.yaml`
sensor-controller crashes.

Error:
```
k logs sensor-controller-86d756bb65-2mjjd -n argo-events
time="2019-03-13T19:36:39Z" level=info msg="watching sensor-controller config map updates"
time="2019-03-13T19:36:39Z" level=info msg="detected ConfigMap update. updating the sensor-controller config."
sensor-controller (version: v0.1.2+a1fa700.dirty) (instance: argo-events) starting2019-03-13T19:36:39Z | info  | msg: node is initialized |  node-message: node-name:webhook-gateway-http:foo node-type:EventDependency sensor-name:webhook-sensor-http sensor-namespace:argo-events
2019-03-13T19:36:39Z | info  | msg: node is initialized |  node-message: node-name:webhook-workflow-trigger node-type:Trigger sensor-name:webhook-sensor-http sensor-namespace:argo-events
ERROR: logging before flag.Parse: E0313 19:36:39.451661       1 runtime.go:69] Observed a panic: "index out of range" (runtime error: index out of range)
/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/runtime/panic.go:44
/home/vaibhav/go/src/github.com/argoproj/argo-events/controllers/sensor/operator.go:122
/home/vaibhav/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:109
/home/vaibhav/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:177
/home/vaibhav/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:170
/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1333
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 29 [running]:
github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x1091e20, 0x1cde580)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/argoproj/argo-events/controllers/sensor.(*sOperationCtx).operate(0xc0001569a0, 0x0, 0x0)
	/home/vaibhav/go/src/github.com/argoproj/argo-events/controllers/sensor/operator.go:122 +0x1631
github.com/argoproj/argo-events/controllers/sensor.(*SensorController).processNextItem(0xc000146360, 0xc0002bc600)
	/home/vaibhav/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:109 +0x24a
github.com/argoproj/argo-events/controllers/sensor.(*SensorController).runWorker(0xc000146360)
	/home/vaibhav/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:177 +0x2b
github.com/argoproj/argo-events/controllers/sensor.(*SensorController).runWorker-fm()
	/home/vaibhav/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:170 +0x2a
github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0000aa110)
	/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0000aa110, 0x3b9aca00, 0x0, 0x2c5d202020202001, 0x0)
	/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0000aa110, 0x3b9aca00, 0x0)
	/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo-events/controllers/sensor.(*SensorController).Run
	/home/vaibhav/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:170 +0x2ff
```

**Expected behavior**
The sensor-controller successfully deploys.

**Environment (please complete the following information):**
I've tried this on minikube on mac:
`minikube version: v0.35.0`
```
NAME       STATUS    ROLES     AGE       VERSION
minikube   Ready     master    14d       v1.13.4
```
and in a cluster environment:
```
NAME                    STATUS     ROLES     AGE       VERSION
kube-master01   Ready      master    12d       v1.13.3
kube-node01     Ready      node      12d       v1.13.3
kube-node03     Ready      node      12d       v1.13.3
```

**Comment by VaibhavPage** [comment]
What is the image tag for controllers, gateway and sensor?

**Comment by pplavetzki** [comment]
```
Containers:
  gateway-controller:
    Container ID:   docker://f3805cf91ff244587afee8fb14a9010b546e3a6edae3f6621e383e7d45af2ed9
    Image:          argoproj/gateway-controller
    Image ID:       docker-pullable://argoproj/gateway-controller@sha256:2e140c744303855ce8beb079dc34d5c480f875e1b0de6685cfc9c8c543550cd9
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 13 Mar 2019 13:09:15 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      GATEWAY_NAMESPACE:              argo-events (v1:metadata.namespace)
      GATEWAY_CONTROLLER_CONFIG_MAP:  gateway-controller-configmap
```
```
Containers:
  sensor-controller:
    Container ID:   docker://a5dbf9affdd82ed42f6d46ecf214656f59dad37f590d02143fad2882eb8003d5
    Image:          argoproj/sensor-controller
    Image ID:       docker-pullable://argoproj/sensor-controller@sha256:85592375f60e5c49bbb2f24ada3c9ba9186c3c4f3bf2bedfe206fe140a1aed7a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 13 Mar 2019 13:08:52 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      SENSOR_NAMESPACE:   argo-events (v1:metadata.namespace)
      SENSOR_CONFIG_MAP:  sensor-controller-configmap
```
```
Controlled By:  Gateway/webhook-gateway-http
Containers:
  gateway-client:
    Container ID:  docker://184f057ab01b94fe085f7b423648871bebb7ce705fe07f7e0908e51f3000ea12
    Image:         argoproj/gateway-client
    Image ID:      docker-pullable://argoproj/gateway-client@sha256:779f4873c38f841143843b57db558ca82da945330e70afab33ab3e74c093612c
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/gateway-client
    State:          Running
      Started:      Wed, 13 Mar 2019 13:15:10 -0700
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 13 Mar 2019 13:15:07 -0700
      Finished:     Wed, 13 Mar 2019 13:15:07 -0700
    Ready:          True
    Restart Count:  1
    Environment:
      GATEWAY_NAMESPACE:                argo-events
      GATEWAY_EVENT_SOURCE_CONFIG_MAP:  webhook-gateway-configmap
      GATEWAY_NAME:                     webhook-gateway-http
      GATEWAY_CONTROLLER_INSTANCE_ID:   argo-events
      GATEWAY_CONTROLLER_NAME:          gateway-controller
      GATEWAY_SERVER_PORT:              9330
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from argo-events-sa-token-d97xw (ro)
  webhook-events:
    Container ID:  docker://0618acb43181b28207f9d2379f23a81489c0215be0c11bd0d5b008537d5eba52
    Image:         argoproj/webhook-gateway
    Image ID:      docker-pullable://argoproj/webhook-gateway@sha256:214e939e4e323e673928acf0c444f72920f6e5c3373be59f6c4414e5ae019aa9
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/webhook-gateway
    State:          Running
      Started:      Wed, 13 Mar 2019 13:15:08 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      GATEWAY_NAMESPACE:                argo-events
      GATEWAY_EVENT_SOURCE_CONFIG_MAP:  webhook-gateway-configmap
      GATEWAY_NAME:                     webhook-gateway-http
      GATEWAY_CONTROLLER_INSTANCE_ID:   argo-events
      GATEWAY_CONTROLLER_NAME:          gateway-controller
      GATEWAY_SERVER_PORT:              9330
```

**Comment by VaibhavPage** [comment]
Can you run everything with v0.8.1 tag?

**Comment by pplavetzki** [comment]
Same error using v0.8.1 tag for gateway and sensor.
```
Containers:
  sensor-controller:
    Container ID:   docker://58c09bb950e5371906d3e0cd002bbe41957825c3bef83070f2435e0b136d5fc1
    Image:          argoproj/sensor-controller:v0.8.1
    Image ID:       docker-pullable://argoproj/sensor-controller@sha256:295e912740a9497101d8d7379bbae417f4038edf87936df6381f8023d286a9d1
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 13 Mar 2019 15:13:19 -0700
      Finished:     Wed, 13 Mar 2019 15:13:19 -0700
    Ready:          False
```

**Comment by VaibhavPage** [comment]
I just tested 0.8.1 and it worked perfectly fine. Can you delete everything and re-install

**Comment by pplavetzki** [comment]
I tried again on both cluster and fresh install of minikube.  No luck using version v0.8.1.  For whatever reason after deploying this manifest:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor-http
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  deploySpec:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor:v0.8.1"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "webhook-gateway-http:foo"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - name: webhook-workflow-trigger
      resource:
        namespace: argo-events
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: hello-world-
            spec:
              entrypoint: whalesay
              templates:
                - name: whalesay
                  container:
                    args:
                      - "hello world"
                    command:
                      - cowsay
                    image: "docker/whalesay:latest"
```
it crashes the sensor-controller.

When I remove this Sensor, the sensor-controller successfully gets back to status=running.

**Comment by ozankabak** [comment]
I am running into the exact same issue as well.

**Comment by monsiper** [comment]
Running into the same exact issue with the resource-gateway and resource-sensor posted under the examples folder. Interestingly, github-gateway and github-sensor work fine.

**Comment by VaibhavPage** [comment]
Not sure why is you are seeing this issue, I ran v0.8.1 again, here is the output of all steps - 

Gateway controller 
```
# The gateway-controller listens for changes on the gateway CRD and creates gateway
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-controller
    spec:
      serviceAccountName: argo-events-sa
      containers:
      - name: gateway-controller
        image: argoproj/gateway-controller:v0.8.1
        imagePullPolicy: Always
        env:
          - name: GATEWAY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GATEWAY_CONTROLLER_CONFIG_MAP
            value: gateway-controller-configmap

```

Sensor controller 
```
# The sensor-controller listens for changes on the sensor CRD and creates sensor executor jobs
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sensor-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sensor-controller
    spec:
      serviceAccountName: argo-events-sa
      containers:
      - name: sensor-controller
        image: argoproj/sensor-controller:v0.8.1
        imagePullPolicy: Always
        env:
          - name: SENSOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SENSOR_CONFIG_MAP
            value: sensor-controller-configmap

```

```
➜  argo-events git:(master) ✗ k create -f hack/k8s/manifests/gateway-controller-deployment.yaml
deployment.apps/gateway-controller created
➜  argo-events git:(master) ✗ k create -f hack/k8s/manifests/sensor-controller-deployment.yaml 
deployment.apps/sensor-controller created
```

```
➜  argo-events git:(master) ✗ k get po
NAME                                   READY   STATUS    RESTARTS   AGE
argo-ui-66cd4c84c7-jhl9v               1/1     Running   16         63d
gateway-controller-86db58c967-b2dw8    1/1     Running   0          73s
sensor-controller-846d9cf86b-cs84n     1/1     Running   0          65s
workflow-controller-6bcfd55469-qj4q6   1/1     Running   17         63d
```

Gateway controller logs - 
```
➜  argo-events git:(master) ✗ k logs gateway-controller-86db58c967-b2dw8 
2019-03-14T10:05:55Z | info  | msg: starting gateway-controller |  controller-namespace:argo-events instance-id:argo-events version:v0.1.2+45bf2f0.dirty
2019-03-14T10:05:55Z | info  | msg: watching gateway-controller config map updates |  controller-namespace:argo-events
2019-03-14T10:05:55Z | info  | msg: detected ConfigMap update. updating the gateway-controller config. |  controller-namespace:argo-events

```

Sensor controller logs - 
```
➜  argo-events git:(master) ✗ k logs sensor-controller-846d9cf86b-cs84n 
time="2019-03-14T10:26:21Z" level=info msg="watching sensor-controller config map updates"
time="2019-03-14T10:26:21Z" level=info msg="detected ConfigMap update. updating the sensor-controller config."
sensor-controller (version: v0.8.0+7554db9.dirty) (instance: argo-events) 
```


Webhook gateway -
```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: webhook-gateway-http
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
    gateway-name: "webhook-gateway-http"
spec:
  configMap: "webhook-gateway-configmap"
  type: "webhook"
  processorPort: "9330"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  eventVersion: "1.0"
  deploySpec:
    metadata:
      name: "webhook-gateway-http"
      labels:
        gateway-name: "webhook-gateway-http"
    spec:
      containers:
        - name: "gateway-client"
          image: "argoproj/gateway-client:v0.8.1"
          imagePullPolicy: "Always"
          command: ["/bin/gateway-client"]
        - name: "webhook-events"
          image: "argoproj/webhook-gateway:v0.8.1"
          imagePullPolicy: "Always"
          command: ["/bin/webhook-gateway"]
      serviceAccountName: "argo-events-sa"
  serviceSpec:
    metadata:
      name: webhook-gateway-svc
    spec:
      selector:
        gateway-name: "webhook-gateway-http"
      ports:
        - port: 12000
          targetPort: 12000
      type: LoadBalancer
  watchers:
    sensors:
      - name: "webhook-sensor-http"
```

Event sources I am running in the gateway configmap- 
```

bar:
 port: "12000"
 endpoint: "/bar"
 method: "POST"

foo:
 port: "12000"
 endpoint: "/foo"
 method: "POST"

index:
 port: "12000"
 endpoint: "/"
 method: "POST"

```


Create webhook gateway
```

➜  argo-events git:(master) ✗ k create -f examples/gateways/webhook-http.yaml     
gateway.argoproj.io/webhook-gateway-http created

```

Gw ctrl logs 
```
➜  argo-events git:(master) ✗ k logs gateway-controller-86db58c967-b2dw8     
2019-03-14T10:05:55Z | info  | msg: starting gateway-controller |  controller-namespace:argo-events instance-id:argo-events version:v0.1.2+45bf2f0.dirty
2019-03-14T10:05:55Z | info  | msg: watching gateway-controller config map updates |  controller-namespace:argo-events
2019-03-14T10:05:55Z | info  | msg: detected ConfigMap update. updating the gateway-controller config. |  controller-namespace:argo-events
2019-03-14T10:12:58Z | info  | msg: operating on the gateway |  name:webhook-gateway-http namespace:argo-events phase:
2019-03-14T10:12:58Z | info  | msg: gateway pod created |  name:webhook-gateway-http namespace:argo-events pod-name:webhook-gateway-http
2019-03-14T10:12:58Z | info  | msg: gateway service is created |  name:webhook-gateway-http namespace:argo-events svc-name:webhook-gateway-svc
2019-03-14T10:12:58Z | info  | msg: gateway state updated successfully |  gateway-phase:Running name:webhook-gateway-http namespace:argo-events
2019-03-14T10:12:58Z | info  | msg: successfully persisted gateway resource update and created K8s event |  name:webhook-gateway-http namespace:argo-events
2019-03-14T10:12:58Z | info  | msg: operating on the gateway |  name:webhook-gateway-http namespace:argo-events phase:Running
2019-03-14T10:12:58Z | info  | msg: gateway is running |  name:webhook-gateway-http namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: operating on the gateway |  name:webhook-gateway-http namespace:argo-events phase:Running
2019-03-14T10:13:11Z | info  | msg: gateway is running |  name:webhook-gateway-http namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: operating on the gateway |  name:webhook-gateway-http namespace:argo-events phase:Running
2019-03-14T10:13:11Z | info  | msg: gateway is running |  name:webhook-gateway-http namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: operating on the gateway |  name:webhook-gateway-http namespace:argo-events phase:Running
2019-03-14T10:13:11Z | info  | msg: gateway is running |  name:webhook-gateway-http namespace:argo-events

```

Gw logs - 
```
➜  argo-events git:(master) ✗ k logs webhook-gateway-http gateway-client 
2019-03-14T10:13:11Z | info  | msg: detected ConfigMap addition. Updating the controller run config. |  config-map:webhook-gateway-configmap gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: event source |  config-key:bar config-value:"port: \"12000\"\nendpoint: \"/bar\"\nmethod: \"POST\"" gateway-name:webhook-gateway-http gateway-namespace:argo-events hash:1011765136
2019-03-14T10:13:11Z | info  | msg: state of the connection |  gateway-name:webhook-gateway-http gateway-namespace:argo-events state:READY
2019-03-14T10:13:11Z | info  | msg: event source |  config-key:foo config-value:"port: \"12000\"\nendpoint: \"/foo\"\nmethod: \"POST\"" gateway-name:webhook-gateway-http gateway-namespace:argo-events hash:3592417010
2019-03-14T10:13:11Z | info  | msg: state of the connection |  gateway-name:webhook-gateway-http gateway-namespace:argo-events state:READY
2019-03-14T10:13:11Z | info  | msg: event source |  config-key:index config-value:"port: \"12000\"\nendpoint: \"/\"\nmethod: \"POST\"" gateway-name:webhook-gateway-http gateway-namespace:argo-events hash:1643745524
2019-03-14T10:13:11Z | info  | msg: state of the connection |  gateway-name:webhook-gateway-http gateway-namespace:argo-events state:READY
2019-03-14T10:13:11Z | info  | msg: event sources hashes |  current-event-sources-keys:null gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: event sources hashes |  gateway-name:webhook-gateway-http gateway-namespace:argo-events updated-event-sources--keys:["1011765136","3592417010","1643745524"]
2019-03-14T10:13:11Z | info  | msg: stale event sources |  event-sources:null gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: new event sources |  event-sources:["1011765136","3592417010","1643745524"] gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: activating new event source |  event-source-name:bar gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: activating new event source |  event-source-name:foo gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: activating new event source |  event-source-name:index gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: event source is valid |  event-source-name:index gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: started listening to events from gateway server |  event-source-name:index gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: received a gateway state update notification |  gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: node |  gateway-name:webhook-gateway-http gateway-namespace:argo-events node-id:1643745524 node-name:index
2019-03-14T10:13:11Z | info  | msg: node is running |  gateway-name:webhook-gateway-http gateway-namespace:argo-events node-message:event_source_is_running node-name:index
2019-03-14T10:13:11Z | info  | msg: event source is valid |  event-source-name:bar gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: event source is valid |  event-source-name:foo gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: gateway state updated successfully |  gateway-name:webhook-gateway-http gateway-namespace:argo-events gateway-phase:Running
2019-03-14T10:13:11Z | info  | msg: detected gateway update. updating gateway watchers |  gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: received a gateway state update notification |  gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: node |  gateway-name:webhook-gateway-http gateway-namespace:argo-events node-id:1011765136 node-name:bar
2019-03-14T10:13:11Z | info  | msg: node is running |  gateway-name:webhook-gateway-http gateway-namespace:argo-events node-message:event_source_is_running node-name:bar
2019-03-14T10:13:11Z | info  | msg: started listening to events from gateway server |  event-source-name:bar gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: gateway state updated successfully |  gateway-name:webhook-gateway-http gateway-namespace:argo-events gateway-phase:Running
2019-03-14T10:13:11Z | info  | msg: received a gateway state update notification |  gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: node |  gateway-name:webhook-gateway-http gateway-namespace:argo-events node-id:3592417010 node-name:foo
2019-03-14T10:13:11Z | info  | msg: node is running |  gateway-name:webhook-gateway-http gateway-namespace:argo-events node-message:event_source_is_running node-name:foo
2019-03-14T10:13:11Z | info  | msg: started listening to events from gateway server |  event-source-name:foo gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: gateway state updated successfully |  gateway-name:webhook-gateway-http gateway-namespace:argo-events gateway-phase:Running
2019-03-14T10:13:11Z | info  | msg: received a gateway state update notification |  gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: detected gateway update. updating gateway watchers |  gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: detected gateway update. updating gateway watchers |  gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: received a gateway state update notification |  gateway-name:webhook-gateway-http gateway-namespace:argo-events
2019-03-14T10:13:11Z | info  | msg: received a gateway state update notification |  gateway-name:webhook-gateway-http gateway-namespace:argo-events

➜  argo-events git:(master) ✗ k logs webhook-gateway-http webhook-events 
starting gateway server
2019-03-14T10:13:11Z | info  | msg: operating on event source |  event-source-name:index
2019-03-14T10:13:11Z | info  | msg: adding route handler |  endpoint:/ event-source-name:index port:12000
2019-03-14T10:13:11Z | info  | msg: route handler added |  endpoint:/ event-source-name:index port:12000
2019-03-14T10:13:11Z | info  | msg: operating on event source |  event-source-name:bar
2019-03-14T10:13:11Z | info  | msg: adding route handler |  endpoint:/bar event-source-name:bar port:12000
2019-03-14T10:13:11Z | info  | msg: route handler added |  endpoint:/bar event-source-name:bar port:12000
2019-03-14T10:13:11Z | info  | msg: operating on event source |  event-source-name:foo
2019-03-14T10:13:11Z | info  | msg: adding route handler |  endpoint:/foo event-source-name:foo port:12000
2019-03-14T10:13:11Z | info  | msg: route handler added |  endpoint:/foo event-source-name:foo port:12000

```

Create webhook sensor

```
➜  argo-events git:(master) ✗ k create -f examples/sensors/webhook-http.yaml                  
sensor.argoproj.io/webhook-sensor-http created

```
Sensor logs 
```
➜  argo-events git:(master) ✗ k logs webhook-sensor-http 
2019-03-14T10:26:44Z | info  | msg: sensor started listening |  port:9300 sensor-name:webhook-sensor-http
2019-03-14T10:26:44Z | info  | msg: watching sensor updates |  sensor-name:webhook-sensor-http

```

Sensor ctrl logs -
```
➜  argo-events git:(master) ✗ k logs sensor-controller-846d9cf86b-n87xw 
time="2019-03-14T10:26:21Z" level=info msg="watching sensor-controller config map updates"
time="2019-03-14T10:26:21Z" level=info msg="detected ConfigMap update. updating the sensor-controller config."
sensor-controller (version: v0.8.0+7554db9.dirty) (instance: argo-events) starting2019-03-14T10:26:38Z | info  | msg: node is initialized |  node-message: node-name:webhook-gateway-http:foo node-type:EventDependency sensor-name:webhook-sensor-http sensor-namespace:argo-events
2019-03-14T10:26:38Z | info  | msg: node is initialized |  node-message: node-name:webhook-workflow-trigger node-type:Trigger sensor-name:webhook-sensor-http sensor-namespace:argo-events
2019-03-14T10:26:38Z | info  | msg: sensor pod is created |  pod-name:webhook-sensor-http sensor-name:webhook-sensor-http sensor-namespace:argo-events
2019-03-14T10:26:38Z | info  | msg: sensor service is created |  sensor-name:webhook-sensor-http sensor-namespace:argo-events svc-name:webhook-sensor-http-svc
2019-03-14T10:26:38Z | info  | msg: marking sensor as active |  sensor-name:webhook-sensor-http sensor-namespace:argo-events
2019-03-14T10:26:38Z | info  | msg: sensor phase updated |  new-phase:Active old-phase: sensor-name:webhook-sensor-http sensor-namespace:argo-events
2019-03-14T10:26:38Z | info  | msg: sensor message updated |  new-message:"listening for events" old-message: sensor-name:webhook-sensor-http sensor-namespace:argo-events
2019-03-14T10:26:38Z | info  | msg: sensor state updated successfully |  phase:Active sensor-name:webhook-sensor-http sensor-namespace:argo-events
2019-03-14T10:26:38Z | info  | msg: successfully persisted sensor resource update and created K8s event |  sensor-name:webhook-sensor-http sensor-namespace:argo-events
2019-03-14T10:26:38Z | info  | msg: sensor is running |  sensor-name:webhook-sensor-http sensor-namespace:argo-events
2019-03-14T10:26:38Z | debug | msg: sensor pod spec unchanged |  pod-name:webhook-sensor-http sensor-name:webhook-sensor-http sensor-namespace:argo-events
2019-03-14T10:26:38Z | debug | msg: sensor service spec unchanged |  sensor-name:webhook-sensor-http sensor-namespace:argo-events service-name:webhook-sensor-http-svc


```

After triggering a HTTP post, the workflow gets created 
```
➜  argo-events git:(master) ✗ k logs webhook-sensor-http                     
2019-03-14T10:26:44Z | info  | msg: sensor started listening |  port:9300 sensor-name:webhook-sensor-http
2019-03-14T10:26:44Z | info  | msg: watching sensor updates |  sensor-name:webhook-sensor-http
2019-03-14T10:29:35Z | info  | msg: received an event from gateway |  sensor-name:webhook-sensor-http
2019-03-14T10:29:35Z | info  | msg: message successfully sent over internal queue |  event-source-name:webhook-gateway-http:foo sensor-name:webhook-sensor-http
2019-03-14T10:29:35Z | info  | msg: received event notification |  event-dependency-name:webhook-gateway-http:foo sensor-name:webhook-sensor-http
2019-03-14T10:29:35Z | info  | msg: completed |  node-name:webhook-gateway-http:foo sensor-name:webhook-sensor-http type:EventDependency
2019-03-14T10:29:35Z | info  | msg: all event dependencies are marked completed, processing triggers |  sensor-name:webhook-sensor-http
2019-03-14T10:29:35Z | info  | msg: created api resource |  api:workflows group-version:v1alpha1 sensor-name:webhook-sensor-http
2019-03-14T10:29:35Z | info  | msg: created object |  kind:Workflow name:hello-world-8g8cn sensor-name:webhook-sensor-http
2019-03-14T10:29:35Z | info  | msg: completed |  node-name:webhook-workflow-trigger sensor-name:webhook-sensor-http type:Trigger
2019-03-14T10:29:36Z | info  | msg: sensor state updated successfully |  phase:Active sensor-name:webhook-sensor-http
2019-03-14T10:29:36Z | info  | msg: successfully persisted sensor resource update and created K8s event |  sensor-name:webhook-sensor-http
2019-03-14T10:29:36Z | info  | msg: sensor resource update |  sensor-name:webhook-sensor-http
2019-03-14T10:29:36Z | info  | msg: sensor state updated successfully |  phase:Active sensor-name:webhook-sensor-http
2019-03-14T10:29:36Z | info  | msg: successfully persisted sensor resource update and created K8s event |  sensor-name:webhook-sensor-http

```


```
➜  argo-events git:(master) ✗ k get po
NAME                                   READY   STATUS      RESTARTS   AGE
argo-ui-66cd4c84c7-jhl9v               1/1     Running     16         63d
gateway-controller-86db58c967-b2dw8    1/1     Running     0          24m
hello-world-8g8cn                      0/2     Completed   0          56s
sensor-controller-846d9cf86b-n87xw     1/1     Running     0          4m16s
webhook-gateway-http                   2/2     Running     1          17m
webhook-sensor-http                    1/1     Running     0          3m53s
workflow-controller-6bcfd55469-qj4q6   1/1     Running     17         63d

```

**Comment by VaibhavPage** [comment]
```➜  argo-events git:(master) ✗ k create -f hack/k8s/manifests/gateway-controller-deployment.yamldeployment.apps/gateway-controller created➜  argo-events git:(master) ✗ k create -f hack/k8s/manifests/sensor-controller-deployment.yaml deployment.apps/sensor-controller created```

**Comment by VaibhavPage** [comment]
I've also published a patch v0.8.2 which reflects the master branch. Give it a try if v0.8.1 doesn't work.

**Comment by tunaaksoy** [comment]
I was having the same issue this morning. Switching to v0.8.1 worked fine for me. Looks like a recent change in the docker image for the sensor-controller is causing the problems (just guessing). I used the latest docker image in the beginning of this week but changed the imagePullPolicy to IfNotPresent hence did not notice the issue until this morning. Today I tried a fresh deployment and faced the same issue as described above.

**Comment by pplavetzki** [comment]
After re-trying one more time this morning using v0.8.1 for all the images, the above example worked as expected.  Not quite sure what was different this time around but works in the minikube environment.

Many thanks!

**Comment by tunaaksoy** [comment]
@pplavetzki have you tried triggering workflows after you changed it to v0.8.1? I was able trigger 1 workflow but then the webhook-sensor-http pod disappeared and I was not able run another workflow again.

**Comment by pplavetzki** [comment]
@tunaaksoy I was able to execute the hello-world workflow multiple times, without problems.

One thing I didn't mention is that I also tried the v0.8.2 tag and received the error that you are describing.  The webhook-sensor-http pod disappeared and the sensor-controller started throwing configMap errors.

**Comment by tunaaksoy** [comment]
Thank you @pplavetzki. I'll take another look and try to find out what I did wrong.

**Comment by VaibhavPage** [comment]
Yeah, although v0.8.2 has latest changes, the examples in master branch needs to be updated to make them work with v0.8.2 . So I would suggest to v0.8.1 for now. We will be releasing v0.9 in next couple of days.
