### ISSUE TITLE
Sensor controller segfaults when adding sensor without eventProtocol

### ISSUE THREAD

**Issue by ptemmer** [argoproj/argo-events#394]
**To Reproduce**
1. Add a sensor manifest that lacks an eventProtocol entry
2. The sensor-controller abruptly ends with a segmentation fault

```
time="2019-11-06T14:19:10Z" level=info msg="watching sensor-controller config map updates"
INFO[2019-11-06 14:19:10] starting sensor controller                    instance-id=argo-events version=v0.10+f0330c9
time="2019-11-06T14:19:10Z" level=info msg="detected EventSource update. updating the sensor-controller config."
ERROR: logging before flag.Parse: E1106 14:20:19.396652       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/Users/vpage/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/Users/vpage/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/Users/vpage/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/validate.go:49
/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/operator.go:131
/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/operator.go:106
/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:126
/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:232
/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:225
/Users/vpage/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/Users/vpage/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/Users/vpage/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfa2215]

goroutine 48 [running]:
github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/vpage/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x10bc560, 0x1d795e0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/argoproj/argo-events/controllers/sensor.ValidateSensor(0xc0004a4600, 0x12208f9, 0x26)
	/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/validate.go:49 +0xe5
github.com/argoproj/argo-events/controllers/sensor.(*sOperationCtx).createSensorResources(0xc0004f4640, 0x127d8b8, 0xc0004f4640)
	/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/operator.go:131 +0x43
github.com/argoproj/argo-events/controllers/sensor.(*sOperationCtx).operate(0xc0004f4640, 0x0, 0x0)
	/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/operator.go:106 +0x1c5
github.com/argoproj/argo-events/controllers/sensor.(*SensorController).processNextItem(0xc00010c000, 0xc0000ac900)
	/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:126 +0x1b8
github.com/argoproj/argo-events/controllers/sensor.(*SensorController).runWorker(0xc00010c000)
	/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:232 +0x2b
github.com/argoproj/argo-events/controllers/sensor.(*SensorController).runWorker-fm()
	/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:225 +0x2a
github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000410c80)
	/Users/vpage/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000410c80, 0x3b9aca00, 0x0, 0xc000045f01, 0x0)
	/Users/vpage/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000410c80, 0x3b9aca00, 0x0)
	/Users/vpage/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo-events/controllers/sensor.(*SensorController).Run
	/Users/vpage/go/src/github.com/argoproj/argo-events/controllers/sensor/controller.go:225 +0x99c
```

**Expected behavior**
Sensor controller should remain running and at most reject the new sensor

**Environment (please complete the following information):**
- Version: v0.10

**Additional context**

**Comment by VaibhavPage** [comment]
Closing the issue. Please use v0.13.0
