### ISSUE TITLE
AWS SNS panic at first start of gateway-client 

### ISSUE THREAD

**Issue by clementlecorre** [argoproj/argo-events#413]
**Describe the bug**

I have panic during the first start of gateway-client

```
panic: failed to connect to server on port 9330

goroutine 1 [running]:
main.main()
	/home/vaibhav/go/src/github.com/argoproj/argo-events/gateways/cmd/main.go:53 
```

**To Reproduce**

You must have an argo event environment with version v0.11

1.  Simulate a restart : `kubectl -n argo delete pod aws-sns-gateway`

```
> kubectl -n argo get pod aws-sns-gateway
NAME              READY   STATUS              RESTARTS   AGE
aws-sns-gateway   0/2     ContainerCreating   0          15s

```
2. Pod restart = 1, why ?

```
kubectl -n argo get pod aws-sns-gateway
NAME              READY   STATUS    RESTARTS   AGE
aws-sns-gateway   2/2     Running   1          68s
```
3. Show previous logs and see error

```
> kubectl -n argo  logs -f aws-sns-gateway -c gateway-client -p
panic: failed to connect to server on port 9330

goroutine 1 [running]:
main.main()
	/home/vaibhav/go/src/github.com/argoproj/argo-events/gateways/cmd/main.go:53 +0x22a
```

**Expected behavior**

Not having a restart. Implementing connection retry?

**Environment :**

 - k8s : v1.14.8-eks
 - Argo events : v0.11
- Argo workflow : v2.4.2

**Comment by VaibhavPage** [comment]
Can you try with v0.12-rc?
