### ISSUE TITLE
Code generation with ./hack/update-codegen.sh fails

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo-events#46]
**Describe the bug**

I was trying to add some additional fields to a struct in `types.go`. I added the code and tried to run `./hack/update-codegen.sh` to generate new code. However, that failed with the following error:
```
$ ./hack/update-codegen.sh
bash: ./vendor/k8s.io/code-generator/generate-groups.sh: No such file or directory
```

**Expected behavior**
`./hack/update-codegen.sh` should execute without any errors.

**Comment by shrinandj** [comment]
I manually created the file `./vendor/k8s.io/code-generator/generate-groups.sh` and copied the [contents](https://raw.githubusercontent.com/kubernetes/code-generator/master/generate-groups.sh) from here into it. However, that failed with the following errors:
```
$ ./hack/update-codegen.sh
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+ '[' 6 -lt 4 ']'
+ '[' deepcopy,client,informer,lister == --help ']'
+ GENS=deepcopy,client,informer,lister
+ OUTPUT_PKG=github.com/argoproj/argo-events/pkg/client
+ APIS_PKG=github.com/argoproj/argo-events/pkg/apis
+ GROUPS_WITH_VERSIONS=sensor:v1alpha1
+ shift 4
++ dirname ./vendor/k8s.io/code-generator/generate-groups.sh
+ cd ./vendor/k8s.io/code-generator
+ go install ./cmd/defaulter-gen ./cmd/client-gen ./cmd/lister-gen ./cmd/informer-gen ./cmd/deepcopy-gen
+ FQ_APIS=()
+ for GVs in ${GROUPS_WITH_VERSIONS}
+ IFS=:
+ read G Vs
+ for V in ${Vs//,/ }
+ FQ_APIS+=(${APIS_PKG}/${G}/${V})
+ '[' deepcopy,client,informer,lister = all ']'
+ grep -qw deepcopy
+ echo 'Generating deepcopy funcs'
Generating deepcopy funcs
++ codegen::join , github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
++ local IFS=,
++ shift
++ echo github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
+ /Users/sjavadekar/ws/go/bin/deepcopy-gen --input-dirs github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1 -O zz_generated.deepcopy --bounding-dirs github.com/argoproj/argo-events/pkg/apis --go-header-file ./hack/../hack/custom-boilerplate.go.txt
+ '[' deepcopy,client,informer,lister = all ']'
+ grep -qw client
+ echo 'Generating clientset for sensor:v1alpha1 at github.com/argoproj/argo-events/pkg/client/clientset'
Generating clientset for sensor:v1alpha1 at github.com/argoproj/argo-events/pkg/client/clientset
++ codegen::join , github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
++ local IFS=,
++ shift
++ echo github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
+ /Users/sjavadekar/ws/go/bin/client-gen --clientset-name versioned --input-base '' --input github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1 --output-package github.com/argoproj/argo-events/pkg/client/clientset --go-header-file ./hack/../hack/custom-boilerplate.go.txt
F0718 16:34:25.387671   12364 main.go:69] Error: Failed making a parser: unable to add directory "k8s.io/apimachinery/pkg/apimachinery/registered": unable to import "k8s.io/apimachinery/pkg/apimachinery/registered": cannot find package "k8s.io/apimachinery/pkg/apimachinery/registered" in any of:
	/Users/sjavadekar/ws/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/apimachinery/registered (vendor tree)
	/usr/local/Cellar/go/1.10.3/libexec/src/k8s.io/apimachinery/pkg/apimachinery/registered (from $GOROOT)
	/Users/sjavadekar/ws/go/src/k8s.io/apimachinery/pkg/apimachinery/registered (from $GOPATH)
goroutine 1 [running]:
github.com/argoproj/argo-events/vendor/github.com/golang/glog.stacks(0xc42674db00, 0xc42675a000, 0x26f, 0x2c4)
	/Users/sjavadekar/ws/go/src/github.com/argoproj/argo-events/vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/argoproj/argo-events/vendor/github.com/golang/glog.(*loggingT).output(0x150d020, 0xc400000003, 0xc425a3e9a0, 0x14e9920, 0x7, 0x45, 0x0)
	/Users/sjavadekar/ws/go/src/github.com/argoproj/argo-events/vendor/github.com/golang/glog/glog.go:720 +0x32d
github.com/argoproj/argo-events/vendor/github.com/golang/glog.(*loggingT).printf(0x150d020, 0xc400000003, 0x12ffeee, 0x9, 0xc426303e48, 0x1, 0x1)
	/Users/sjavadekar/ws/go/src/github.com/argoproj/argo-events/vendor/github.com/golang/glog/glog.go:655 +0x14b
github.com/argoproj/argo-events/vendor/github.com/golang/glog.Fatalf(0x12ffeee, 0x9, 0xc426303e48, 0x1, 0x1)
	/Users/sjavadekar/ws/go/src/github.com/argoproj/argo-events/vendor/github.com/golang/glog/glog.go:1148 +0x67
main.main()
	/Users/sjavadekar/ws/go/src/github.com/argoproj/argo-events/vendor/k8s.io/code-generator/cmd/client-gen/main.go:69 +0x53f
```
