### ISSUE TITLE
Webhook unit test panics with invalid memory address

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo-events#53]
**Describe the bug**
Unit tests for webhook signals panic with the following stacktrace:

```
=== RUN   TestSignal/delete
2018/07/23 04:23:25 server successfully shutdown
2018/07/23 04:23:25 received a request from 'localhost:9000'
2018/07/23 04:23:25 server successfully shutdown
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x831f6e]
goroutine 10 [running]:
testing.tRunner.func1(0xc420240000)
        /usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0x17ad5a0, 0x22762b0)
        /usr/local/go/src/runtime/panic.go:491 +0x2a2
net/http.(*Server).Shutdown(0xc420274000, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2506 +0x20e
github.com/argoproj/argo-events/signals/webhook.(*webhook).Stop(0xc4203faa20, 0xc420124400, 0xc4203ece10)
        /go/src/github.com/argoproj/argo-events/signals/webhook/signal.go:105 +0x89
github.com/argoproj/argo-events/signals/webhook.makeAPIRequest(0xc420240000, 0x18f0592, 0x6, 0x18f16cf, 0x7)
        /go/src/github.com/argoproj/argo-events/signals/webhook/signal_test.go:70 +0x72d
github.com/argoproj/argo-events/signals/webhook.testDeleteRequest(0xc420240000)
        /go/src/github.com/argoproj/argo-events/signals/webhook/signal_test.go:85 +0x63
testing.tRunner(0xc420240000, 0x1970078)
        /usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:789 +0x569
FAIL    github.com/argoproj/argo-events/signals/webhook 0.559s
```

**To Reproduce**
http://argo.applatix.net/workflows/default/argo-events-ci-cprp2?tab=workflow&nodeId=argo-events-ci-cprp2-613907525&sidePanel=logs%3Aargo-events-ci-cprp2-613907525%3Amain

**Expected behavior**
Unit tests should succeed.

**Comment by shrinandj** [comment]
Looks like the unit tests start a webserver at a fixed address of 9000. There might be a problem if two unit tests run concurrently that use the same port.

**Comment by magaldima** [comment]
Thanks for creating this issue, I was noticing the same patterns in some of the tests. I think the port may be the problem. Why would the tests would be running concurrently since the `t.Parallel()` is not set for these tests?

Do you think it could have something to do with the way `Shutdown()` was invoked with a nil context? In #49 I changed this to: `err := srv.Shutdown(context.TODO())`.
